import os
import django
from django.db import connection

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'ShopSmartAI.settings')
django.setup()

SQL_STATEMENTS = [
    "CREATE TABLE \"users_user\" (\"password\" varchar(128) NOT NULL, \"is_superuser\" boolean NOT NULL, \"id\" uuid NOT NULL PRIMARY KEY, \"email\" varchar(254) NOT NULL UNIQUE, \"first_name\" varchar(80) NOT NULL, \"last_name\" varchar(80) NOT NULL, \"phone\" varchar(20) NOT NULL, \"avatar\" varchar(100) NULL, \"is_active\" boolean NOT NULL, \"is_staff\" boolean NOT NULL, \"is_verified\" boolean NOT NULL, \"bio\" text NOT NULL, \"date_of_birth\" date NULL, \"gender\" varchar(10) NOT NULL, \"preferred_categories\" jsonb NOT NULL, \"ai_profile_data\" jsonb NOT NULL, \"date_joined\" timestamp with time zone NOT NULL, \"last_login\" timestamp with time zone NULL, \"updated_at\" timestamp with time zone NOT NULL);",
    "CREATE TABLE \"users_user_groups\" (\"id\" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, \"user_id\" uuid NOT NULL, \"group_id\" integer NOT NULL);",
    "CREATE TABLE \"users_user_user_permissions\" (\"id\" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, \"user_id\" uuid NOT NULL, \"permission_id\" integer NOT NULL);",
    "CREATE TABLE \"users_address\" (\"id\" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, \"label\" varchar(50) NOT NULL, \"address_type\" varchar(10) NOT NULL, \"full_name\" varchar(120) NOT NULL, \"phone\" varchar(20) NOT NULL, \"address_line1\" varchar(200) NOT NULL, \"address_line2\" varchar(200) NOT NULL, \"city\" varchar(100) NOT NULL, \"state\" varchar(100) NOT NULL, \"country\" varchar(100) NOT NULL, \"postal_code\" varchar(20) NOT NULL, \"is_default\" boolean NOT NULL, \"created_at\" timestamp with time zone NOT NULL, \"user_id\" uuid NOT NULL);",
    "CREATE TABLE \"users_emailverificationtoken\" (\"id\" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, \"token\" uuid NOT NULL UNIQUE, \"created_at\" timestamp with time zone NOT NULL, \"expires_at\" timestamp with time zone NOT NULL, \"user_id\" uuid NOT NULL UNIQUE);",
    "CREATE TABLE \"users_passwordresettoken\" (\"id\" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, \"token\" uuid NOT NULL UNIQUE, \"created_at\" timestamp with time zone NOT NULL, \"expires_at\" timestamp with time zone NOT NULL, \"used\" boolean NOT NULL, \"user_id\" uuid NOT NULL);",
    "CREATE INDEX \"users_user_email_243f6e77_like\" ON \"users_user\" (\"email\" varchar_pattern_ops);",
    "ALTER TABLE \"users_user_groups\" ADD CONSTRAINT \"users_user_groups_user_id_group_id_b88eab82_uniq\" UNIQUE (\"user_id\", \"group_id\");",
    "ALTER TABLE \"users_user_groups\" ADD CONSTRAINT \"users_user_groups_user_id_5f6f5a90_fk_users_user_id\" FOREIGN KEY (\"user_id\") REFERENCES \"users_user\" (\"id\") DEFERRABLE INITIALLY DEFERRED;",
    "ALTER TABLE \"users_user_groups\" ADD CONSTRAINT \"users_user_groups_group_id_9afc8d0e_fk_auth_group_id\" FOREIGN KEY (\"group_id\") REFERENCES \"auth_group\" (\"id\") DEFERRABLE INITIALLY DEFERRED;",
    "CREATE INDEX \"users_user_groups_user_id_5f6f5a90\" ON \"users_user_groups\" (\"user_id\");",
    "CREATE INDEX \"users_user_groups_group_id_9afc8d0e\" ON \"users_user_groups\" (\"group_id\");",
    "ALTER TABLE \"users_user_user_permissions\" ADD CONSTRAINT \"users_user_user_permissions_user_id_permission_id_43338c45_uniq\" UNIQUE (\"user_id\", \"permission_id\");",
    "ALTER TABLE \"users_user_user_permissions\" ADD CONSTRAINT \"users_user_user_permissions_user_id_20aca447_fk_users_user_id\" FOREIGN KEY (\"user_id\") REFERENCES \"users_user\" (\"id\") DEFERRABLE INITIALLY DEFERRED;",
    "ALTER TABLE \"users_user_user_permissions\" ADD CONSTRAINT \"users_user_user_perm_permission_id_0b93982e_fk_auth_perm\" FOREIGN KEY (\"permission_id\") REFERENCES \"auth_permission\" (\"id\") DEFERRABLE INITIALLY DEFERRED;",
    "CREATE INDEX \"users_user_user_permissions_user_id_20aca447\" ON \"users_user_user_permissions\" (\"user_id\");",
    "CREATE INDEX \"users_user_user_permissions_permission_id_0b93982e\" ON \"users_user_user_permissions\" (\"permission_id\");",
    "ALTER TABLE \"users_address\" ADD CONSTRAINT \"users_address_user_id_4c106ba4_fk_users_user_id\" FOREIGN KEY (\"user_id\") REFERENCES \"users_user\" (\"id\") DEFERRABLE INITIALLY DEFERRED;",
    "CREATE INDEX \"users_address_user_id_4c106ba4\" ON \"users_address\" (\"user_id\");",
    "ALTER TABLE \"users_emailverificationtoken\" ADD CONSTRAINT \"users_emailverificationtoken_user_id_d239ee38_fk_users_user_id\" FOREIGN KEY (\"user_id\") REFERENCES \"users_user\" (\"id\") DEFERRABLE INITIALLY DEFERRED;",
    "CREATE INDEX \"users_passwordresettoken_user_id_2355945a\" ON \"users_passwordresettoken\" (\"user_id\");",
    "ALTER TABLE \"users_passwordresettoken\" ADD CONSTRAINT \"users_passwordresettoken_user_id_2355945a_fk_users_user_id\" FOREIGN KEY (\"user_id\") REFERENCES \"users_user\" (\"id\") DEFERRABLE INITIALLY DEFERRED;",
]

with connection.cursor() as cursor:
    cursor.execute("SELECT tablename FROM pg_tables WHERE schemaname='public' AND tablename='users_user'")
    if cursor.fetchone():
        print('users_user already exists; skipping table creation')
    else:
        print('creating users tables...')
        for stmt in SQL_STATEMENTS:
            cursor.execute(stmt)
        print('created users tables')

    cursor.execute("SELECT 1 FROM django_migrations WHERE app=%s AND name=%s", ['users', '0001_initial'])
    if cursor.fetchone():
        print('users.0001_initial is already recorded')
    else:
        cursor.execute("INSERT INTO django_migrations (app, name, applied) VALUES (%s, %s, now())", ['users', '0001_initial'])
        print('recorded users.0001_initial in django_migrations')
