# Generated by Django 6.0.6 on 2026-06-22 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_companyvalue_teammember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySalesSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('order_count', models.PositiveIntegerField(default=0)),
                ('units_sold', models.PositiveIntegerField(default=0)),
                ('avg_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('new_customers', models.PositiveIntegerField(default=0)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProductAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views_7d', models.PositiveIntegerField(default=0)),
                ('views_30d', models.PositiveIntegerField(default=0)),
                ('revenue_7d', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('revenue_30d', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('conversion_rate', models.FloatField(default=0.0)),
                ('return_rate', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='products.product')),
            ],
            options={
                'ordering': ['-revenue_30d'],
            },
        ),
        migrations.CreateModel(
            name='SalesForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField(db_index=True)),
                ('predicted_revenue', models.DecimalField(decimal_places=2, max_digits=14)),
                ('lower_bound', models.DecimalField(decimal_places=2, max_digits=14)),
                ('upper_bound', models.DecimalField(decimal_places=2, max_digits=14)),
                ('confidence', models.FloatField(default=0.8)),
                ('model_version', models.CharField(blank=True, max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['forecast_date'],
                'unique_together': {('forecast_date', 'model_version')},
            },
        ),
        migrations.CreateModel(
            name='UserBehaviorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('event', models.CharField(choices=[('page_view', 'Page View'), ('search', 'Search'), ('product_view', 'Product View'), ('add_cart', 'Add to Cart'), ('checkout', 'Checkout Start'), ('purchase', 'Purchase')], max_length=20)),
                ('page', models.CharField(blank=True, max_length=300)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', 'created_at'], name='analytics_u_event_ed04e1_idx')],
            },
        ),
    ]
