# Generated by Django 6.0.6 on 2026-06-22 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_companyvalue_teammember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommenderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('model_path', models.CharField(max_length=500)),
                ('n_users', models.PositiveIntegerField(default=0)),
                ('n_products', models.PositiveIntegerField(default=0)),
                ('embedding_dim', models.PositiveIntegerField(default=64)),
                ('train_loss', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-trained_at'],
            },
        ),
        migrations.CreateModel(
            name='SimilarProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_products', to='products.product')),
                ('similar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to', to='products.product')),
            ],
            options={
                'ordering': ['-score'],
                'unique_together': {('product', 'similar')},
            },
        ),
        migrations.CreateModel(
            name='UserProductInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction', models.CharField(choices=[('view', 'View'), ('wishlist', 'Wishlist'), ('cart', 'Add to Cart'), ('purchase', 'Purchase')], max_length=10)),
                ('weight', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interactions', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'product'], name='ai_recommen_user_id_0c7c21_idx'), models.Index(fields=['user', 'interaction'], name='ai_recommen_user_id_efe18a_idx')],
            },
        ),
    ]
