# Generated by Django 6.0.6 on 2026-06-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloatingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(help_text='Price in KES')),
                ('discount_percentage', models.IntegerField(blank=True, help_text='Optional: e.g., 20 for -20%', null=True)),
                ('image', models.ImageField(upload_to='floating_products/')),
                ('card_type', models.CharField(choices=[('big', 'Big Card (Air Max Slot)'), ('small', 'Small Card (Leather Tote Slot)')], max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
